dbdata:
  image: andreagrandi/postgresql:9.3
  volumes:
    - /var/lib/postgresql
  command: /bin/true

db:
  image: andreagrandi/postgresql:9.3
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"
